name: ALN CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup PowerShell
        uses: actions/setup-powershell@v2
      - name: Run Tests
        run: pwsh ./tests/run-pester.ps1
