name: ALN CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  packages: write

env:
  ALN_VERSION: 5.0.0
  COMPLIANCE_SCORE_THRESHOLD: 98.5
  SYSTEM_HEALTH_THRESHOLD: 95.0
  DOCKER_IMAGE_NAME: aln-core
  DOCKER_REGISTRY: ghcr.io

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up ALN
        run: |
          curl -s https://aln-lang.com/install.sh | bash
          aln --version

      - name: Build ALN Core
        run: |
          cd aln-core
          make build

      - name: Run ALN Tests
        run: |
          cd aln-core
          make test

      - name: Validate Compliance
        run: |
          cd aln-core
          aln compliance validate --threshold $COMPLIANCE_SCORE_THRESHOLD

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_REGISTRY }}/${{ github.repository_owner }}/${{ env.DOCKER_IMAGE_NAME }}:latest
            ${{ env.DOCKER_REGISTRY }}/${{ github.repository_owner }}/${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}

      - name: Deploy to Staging
        if: github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.STAGING_USER }}
          key: ${{ secrets.STAGING_SSH_KEY }}
          script: |
            cd /opt/aln
            git pull origin main
            docker pull ${{ env.DOCKER_REGISTRY }}/${{ github.repository_owner }}/${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}
            docker-compose -f docker-compose.staging.yml up -d

      - name: Run Compliance Audit
        run: |
          cd aln-core
          aln compliance audit --environment staging

  production-deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Production
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.PRODUCTION_HOST }}
          username: ${{ secrets.PRODUCTION_USER }}
          key: ${{ secrets.PRODUCTION_SSH_KEY }}
          script: |
            cd /opt/aln
            git pull origin main
            docker pull ${{ env.DOCKER_REGISTRY }}/${{ github.repository_owner }}/${{ env.DOCKER_IMAGE_NAME }}:latest
            docker-compose -f docker-compose.prod.yml up -d --force-recreate
            aln compliance verify --environment production

      - name: Run Production Compliance Check
        run: |
          aln compliance verify --environment production
          echo "Compliance score: $ALN_COMPLIANCE_SCORE"
          if [ $(echo "$ALN_COMPLIANCE_SCORE < $COMPLIANCE_SCORE_THRESHOLD" | bc) -eq 1 ]; then
            echo "Compliance score below threshold. Deployment failed."
            exit 1
          fi
