name: Deploy ALN Ecosystem

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          ghcr.io/${{ github.repository }}/aln-ecosystem:${{ github.sha }}
          ghcr.io/${{ github.repository }}/aln-ecosystem:latest

    - name: Deploy success notification
      run: |
        echo "🎉 ALN Ecosystem deployed successfully!"
        echo "Image: ghcr.io/${{ github.repository }}/aln-ecosystem:${{ github.sha }}"
