```yaml
apiVersion: v1
kind: Service
metadata:
  name: aln-core-service
  namespace: aln-ecosystem
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  - port: 8443
    targetPort: 8443
    name: https
  selector:
    app: aln-ecosystem
```
