name: ALN-Balanced-Main

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  lint-and-validate:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: YAML and File Structure Lint
        run: |
          pwsh ./CScripts/lint-validate-workflow.ps1

  volatility-balance-audit:
    runs-on: windows-latest
    needs: lint-and-validate
    steps:
      - name: Assess System/Repo Volatility
        run: |
          pwsh ./CScripts/volatility-balance-audit.ps1

  ci-build-test:
    runs-on: windows-latest
    needs: volatility-balance-audit
    steps:
      - name: Build and Test
        run: |
          pwsh ./CScripts/build-and-test.ps1

  local-emulation-check:
    runs-on: windows-latest
    needs: ci-build-test
    steps:
      - name: Emulate Locally for Parity
        run: |
          pwsh ./CScripts/local-emulation.ps1

  adaptive-remediation:
    runs-on: windows-latest
    needs: [local-emulation-check]
    steps:
      - name: AI Logic Hotpatch
        run: |
          pwsh ./CScripts/adaptive-remediation-hotpatch.ps1

  notify-and-log:
    runs-on: windows-latest
    needs: [adaptive-remediation]
    steps:
      - name: Send Status/Balance Report
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
        run: |
          pwsh ./CScripts/report-devops-balance.ps1
