name: Repo Backup
on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'
jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Archive repository content
        run: tar czf backup.tar.gz *
      - name: Upload to alternate storage
        uses: actions/upload-artifact@v4
        with:
          name: repo-backup
          path: backup.tar.gz
