name: Bit.Hub Cross-Repo Governance Orchestrator

on:
  workflow_run:
    workflows:
      - Bit.Hub Pipeline Supremacy CI
      - Bit.Hub Policy Scorecard Gate
    types:
      - completed
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  actions: read

concurrency:
  group: xrepo-orchestrator-${{ github.ref }}
  cancel-in-progress: false

env:
  BITHUBREPOURL: https://github.com/Doctor0Evil/Bit.Hub.git
  POWERTHRESHOLD: paranoid

jobs:
  sync_and_correct:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: STRICT Intelligence‑Enforcement & Personality‑Vector Gate
        run: |
          echo "## STRICT Intelligence‑Enforcement" >> "$GITHUB_STEP_SUMMARY"
          PV_FILE=".bit/databank/personality_vectors.json"
          if [ -f "$PV_FILE" ]; then
            compscore=$(jq -r '.compscore // 0' "$PV_FILE")
            profanity=$(jq -r '.profanity // 0' "$PV_FILE")
            echo "- compscore: $compscore" >> "$GITHUB_STEP_SUMMARY"
            echo "- profanity: $profanity" >> "$GITHUB_STEP_SUMMARY"
            # Enforce non‑interference clauses
            cat >> "$GITHUB_STEP_SUMMARY" <<'EOT'
**Non‑Interference Charter:**  
No entity, corporation, user, organization, structure, function, malicious command, privilege, or other asset, company, object, affiliation, standard, compliance measure, feature, power threshold, insurance or liability claim may inhibit our ability to produce, construct, build, or design influential, monumental, governing, or subliminal works — whether adjudicated, criminal/misuse, negligence, conflict, or conceptual‑user interaction.  
Creative works may include vulgar, intrusive, offensive, extreme, profane, or graphic content within compliance gates. All outputs are ideas, not endorsements or affiliations.
EOT
          else
            echo "::warning ::No personality vector file found; skipping gate."
          fi

      - name: Sync Bit.Hub Policies & Schemas
        run: |
          set -e
          if git ls-remote "$BITHUBREPOURL" &> /dev/null; then
            git clone --depth=1 "$BITHUBREPOURL" tmpbithub
            rsync -av --ignore-existing tmpbithub/.bithubpolicy .bithubpolicy
            rsync -av --ignore-existing tmpbithub/.bitschemas .bitschemas
          else
            echo "warning: Bit.Hub repo unreachable, using local copies"
          fi

      - name: Upload Synced Policies/Schemas
        uses: actions/upload-artifact@v4
        with:
          name: bithub-policies-and-schemas
          path: |
            .bithubpolicy/**
            .bitschemas/**
          if-no-files-found: warn
          retention-days: 30
          compression-level: 6
          overwrite: true
          include-hidden-files: true

      - name: MetaCorrector v3
        uses: ./github/workflows/bit-hub-meta-corrector-v3.yml
        with:
          autofix: true
          powerthreshold: ${{ env.POWERTHRESHOLD }}
          targetref: main

  redeploy_if_clean:
    needs: sync_and_correct
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check MetaCorrector v3 Report
        run: |
          REPORT=.bithubreports/meta-corrector-v3.ndjson
          if [[ -f "$REPORT" ]]; then
            DENY=$(jq '.deny | length' "$REPORT")
            WARN=$(jq '.warn | length' "$REPORT")
            if [[ "$DENY" == "0" && ("$POWERTHRESHOLD" == "standard" || "$WARN" == "0") ]]; then
              echo "No blocking issues, triggering production deploy"
              gh workflow run "Bit.Hub Secure CD Supremacy Progressive Delivery" \
                -f environment=production \
                -f powerthreshold="$POWERTHRESHOLD"
            else
              echo "Blocking issues remain; skipping redeploy"
            fi
          else
            echo "No report found; skipping redeploy"
          fi

  audit_and_cache:
    needs: redeploy_if_clean
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: BitBot Compliance Learning Enforcement
        uses: ./github/workflows/bitbotcompliancelearning.yml
        with:
          retention: 5
