name: Bit.Hub Decompression Guard

on:
  workflow_dispatch:
  push:
    paths:
      - ".bit/decompression.policy.yml"
      - ".bit/loaders/decompress.sh"

jobs:
  decompress-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install yq
        run: sudo apt-get update && sudo apt-get install -y yq
      - name: Test decompression
        run: |
          .bit/loaders/decompress.sh test-data/sample.zip .bithub/tmp
