name: "Bob the Plumber - fucking.hillarious.cfg"

on:
  workflow_dispatch:
  push:
    branches: [ main, "**" ]
  schedule:
    - cron: "32 3 * * 3"

jobs:
  full-meta-plumber:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ALN Game Repo
        uses: actions/checkout@v4

      - name: Pipe Inspection (Look for Leaks)
        run: |
          echo "🔎 Bob: Inspecting the pipeline for rust and YAML leaks..."
          if [ ! -d ".github/workflows" ]; then
            echo "🚨 PIPE BURST: No workflows found. Bob grabs his wrench!"
            mkdir -p .github/workflows
            echo "#Emergency meta-workflow recovery. Bob was here!" > .github/workflows/bobthebuilder.yml
          fi

      - name: List All Workflows
        run: |
          if [ "$(ls -A .github/workflows 2>/dev/null)" ]; then
            echo "🪠 Bob: Found the following workflows:"
            ls -lh .github/workflows
          else
            echo "🪠 Bob: Dude—your .github/workflows is still EMPTY. I'm patching you with meta-spackle."
            echo "#!real! workflow" > .github/workflows/this-is-real.yml
          fi

      - name: Patch & Reinforce Pipeline Wall
        run: |
          echo "💧 Applying plumber's putty..."
          echo "// Bob’s Rust Be-Gone!" > pipeline-reinforce.js
          echo "console.log('NO MORE LEAKS. Only memes and builds await.');" >> pipeline-reinforce.js

      - name: Comedy Diagnostics (ASCII & Error Stream)
        run: |
          echo "    💦 "
          echo "   /   \\___ "
          echo "  |     o o )  <<<<   PIPELINE FLOOD ALERT   >>>>"
          echo "  |_____/----  "
          echo "  /    \\"
          echo "BOB: \"I see the issue. You had too many commits jammed in here.\""
          echo "PIPE STATUS: ('$now seriously) Fixed!"
          echo "JOKE: What do you call a CI pipe that gets patched at 3am? A workflow with commitment issues! 😆"

      - name: Restore Lost Meta-Rules
        run: |
          if [ ! -f ".github/workflows/bobthebuilder.yml" ]; then
            echo "#Regenerated by Bob-the-Plumber in hellamode." > .github/workflows/bobthebuilder.yml
          fi
          echo "# Joke rule: All errors must rhyme with 'pipeline'" > .github/workflows/rules-meta.yml

      - name: Commit & Push Heroic Repairs
        run: |
          git config --global user.email "bob@plumber.bot"
          git config --global user.name "Bob The Plumber"
          git add .github/workflows/*.yml pipeline-reinforce.js || true
          git commit -am "🧰 Bob patched your pipeline, found lost YAMLs, left a plumber's crack" || true
          git push || true

      - name: Final Log (No Joke, All Hope)
        run: |
          echo "ALL SYSTEMS GO 🚦 | PIPELINE FULLY PATCHED AND ALMOST UNBREAKABLE"
          echo "Bob says: If this ever actually runs, take a screenshot, because you’re in a real meta-simulation ¯\_(ツ)_/¯"
