name: Volatility-Blockchain-Balance

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  volatility-audit-balance:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Volatility Scan
        run: |
          pwsh ./CScripts/volatility-balance-audit.ps1

  blockchain-secure-stabilization:
    runs-on: windows-latest
    needs: volatility-audit-balance
    steps:
      - name: Blockchain Commit Checkpoint
        run: |
          pwsh ./CScripts/blockchain-stabilization-secure.ps1

  notify-devops:
    runs-on: windows-latest
    needs: blockchain-secure-stabilization
    steps:
      - name: Alert Stakeholders
        run: |
          pwsh ./CScripts/report-devops-balance.ps1
